server:
  port: 8901

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: productservice
  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)